### ISSUE TITLE
Is there any implemented code for videograph model in pytorch?

### ISSUE THREAD

**Issue by gongda0e** [facebookresearch/ego-topo#4]
Hello,
I want to experiment the long-term action anticipation models.
I found the timeception model in your code repository, however, I cannot find any code for videograph implemented in pytorch.
I wonder do you use existing models implemented in tensorflow and keras model or reimplement in pytorch?

**Comment by Tushar-N** [comment]
We used the official Keras code from https://github.com/noureldien/videograph and modified the dataloader to match our task.

**Comment by gongda0e** [comment]
Thank you so much!
