### ISSUE TITLE
Feature FPS

### ISSUE THREAD

**Issue by olga-zats** [facebookresearch/ego-topo#7]
Hi! I wanted to see if my understanding of the fps of the extracted feature is correct. For Epic-kitchens they are extracted at 60fps and for EGTEA at 24. Is this the case? Thank you!

**Comment by Tushar-N** [comment]
Yes, that's right. FYI frames are further subsampled to 6FPS [here](https://github.com/facebookresearch/ego-topo/blob/81b5396e2a6ecc44f4d541d48cf4777670e36e42/build_graph/build.py#L89) to build graphs.

**Comment by olga-zats** [comment]
Thank you for the answer!
